/**
 * routes.js — All frontend route path constants
 */
export const ROUTES = {
  HOME: '/',
  SHOP: '/corporate-gifts',
  PRODUCT: '/product/:slug',
  PRODUCT_PATH: (slug) => `/product/${slug}`,
  CATEGORIES: '/categories',
  CATEGORY: '/categories/:id',
  CATEGORY_PATH: (id) => `/categories/${id}`,
  CORPORATE_GIFTS: '/corporate-gifts',
  PERSONALIZED_GIFTS: '/personalized-gifts',
  TOYS: '/toys',
  SEARCH: '/search',
  CART: '/cart',
  CHECKOUT: '/checkout',
  WISHLIST: '/wishlist',
  LOGIN: '/login',
  REGISTER: '/register',
  ORDERS: '/orders',
  ORDER_DETAIL: '/orders/:id',
  ORDER_DETAIL_PATH: (id) => `/orders/${id}`,
  PROFILE: '/profile',
  CONTACT: '/contact',
  ABOUT: '/about',
  FAQ: '/faq',
  TERMS: '/terms-and-conditions',
  TERMS_AND_CONDITIONS: '/terms-and-conditions',
  PRIVACY: '/privacy-policy',
  NOT_FOUND: '*',

  // Admin & Super Admin
  DASHBOARD: '/dashboard',
  ADMIN_LOGIN: '/admin/login',
  SUPER_ADMIN_LOGIN: '/super-admin/login',
  SUPER_ADMIN_DASHBOARD: '/super-admin/dashboard',
  ADMIN_PRODUCTS: '/dashboard/products',
  ADMIN_ORDERS: '/dashboard/orders',
  ADMIN_USERS: '/dashboard/users',
  ADMIN_SETTINGS: '/dashboard/settings',
};
